In [2]:
import numpy as np

In [4]:
ss = [1, 2, 5, 3]
print(ss, ' ', type(ss))
ss2 = np.array(ss)
print(ss, ' ', type(ss2))

[1, 2, 5, 3]   <class 'list'>
[1, 2, 5, 3]   <class 'numpy.ndarray'>


In [10]:
li = list(range(1, 10))
print(li, type(li), id(li[0]), id(li[1]))
print(li * 10)
for i in li:
    print(i * 10, end = ' ')
print ()

print('-' * 20)
num_ar = np.array(li)
print(num_ar, ' ', id(num_ar[0]), ' ', id(num_ar[1]))
print(num_ar * 10)

[1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'> 1874881600 1874881632
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10 20 30 40 50 60 70 80 90 
--------------------
[1 2 3 4 5 6 7 8 9]   87156728   87156728
[10 20 30 40 50 60 70 80 90]


In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row_r1 = a[1, :]
print(row_r1, row_r1.shape)
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)
print()

col_r1 = a[:, 1]
print(col_r1, col_r1.shape)
col_r2 = a[:, 1:2]
print(col_r2, col_r1.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3,)


In [16]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a.shape)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) 

(3, 2)
[1 4 5]
[1 4 5]


In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)
b = np.array([0,2,0,1])
print(a[np.arange(4), b])
a[np.arange(4), b] += 10
print(a)
print()

bool_id = (a > 10)
print(bool_id)
print(a[bool_id])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]

[[ True False False]
 [False False  True]
 [ True False False]
 [False  True  True]]
[11 16 17 21 12]
