In [23]:
import numpy as np

In [24]:
x = np.array([1,2,3])
y = np.array([4,5,6])
condition = np.array([True, False, True])
result = np.where(condition, x, y)
print(result)

aa = np.where(x >= 2)
print(aa)
print(x[aa])
print(np.where(x > 2, "T", "F"))
print(np.where(x > 2, x, x + 100))
print()
      
my = np.random.randn(4,4)
print(my)
#my = np.random.randn(4,4)
#my = np.random.choice(100, 5)
print(np.where(my > 0, 2, my))
print(np.where(my > 0, 1, my * -1))

[1 5 3]
(array([1, 2], dtype=int64),)
[2 3]
['F' 'F' 'T']
[101 102   3]

[[-0.45381731  2.27258411  0.26805692 -1.4062488 ]
 [-0.60228233  2.63169459 -1.05058318  0.57105596]
 [ 0.96098193  0.97911828  1.08882086 -0.26557409]
 [ 0.00327342 -0.71510747 -0.60868412 -1.38754807]]
[[-0.45381731  2.          2.         -1.4062488 ]
 [-0.60228233  2.         -1.05058318  2.        ]
 [ 2.          2.          2.         -0.26557409]
 [ 2.         -0.71510747 -0.60868412 -1.38754807]]
[[0.45381731 1.         1.         1.4062488 ]
 [0.60228233 1.         1.05058318 1.        ]
 [1.         1.         1.         0.26557409]
 [1.         0.71510747 0.60868412 1.38754807]]


In [28]:
aa = np.eye(3)
print("aa=\n", aa) #3x3짜리 단위행렬 만들어짐
bb = np.c_[aa, aa[2]] #aa에다 aa의 2행(세번째 행)을 열로 추가함
print("bb=\n", bb)
cc = np.r_[aa, aa[[2]]]
print("cc=\n", cc) #2행을 행으로 추가함

a = np.array([1,2,3])
print(a)
print(np.c_[a]) #그냥 이렇게 하면 transpose?

aa=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
bb=
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]
cc=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[1 2 3]
[[1]
 [2]
 [3]]


In [27]:
import random

li = [1, 2, 3, 4, 5, 6, 7]
for i in range(5):
    print(li[random.randint(0, len(li) - 1)], end = " ")
    
print()
print(random.sample(li, k = 5))

print()
li = list(range(1, 46))
print(len(li))
print(random.sample(li, k = 6))
print(np.random.choice(li, 6, replace=False))
print(np.random.choice(li, 6, replace=True))
print(np.random.choice(5, 3, replace=True))

ar = ['~', '!', '@', '#', '$', '%', '^']
print(ar)
print(np.random.choice(ar, 3, p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.4]))

7 5 5 3 6 
[3, 2, 1, 7, 6]

45
[30, 9, 37, 4, 35, 31]
[13 20 28  1 24  5]
[ 5 40 20 19 23 13]
[3 3 0]
['~', '!', '@', '#', '$', '%', '^']
['!' '$' '$']
